Repository traPtitech/traPortfolio-Dashboard, pull requests merged in 2024-09, with the labels that each got.

#354 Fix/search form container
  src/pages/Contests.vue
  src/pages/Events.vue
  src/pages/Projects.vue
Labels: Review effort [1-5]: 2

#360 コンテスト・プロジェクト編集画面にplaceholderを追加
  src/pages/ContestEdit.vue
  src/pages/Project.vue
Labels: Review effort [1-5]: 1

#353 Fix/button link
  src/components/Contest/ContestTeams.vue
  src/components/UI/LinkButton.vue
  src/components/User/UserProfileDesktop.vue
  src/components/User/UserProfileMobile.vue
  src/pages/Contest.vue
  src/pages/ContestEdit.vue
  src/pages/ContestNew.vue
  src/pages/ContestTeamEdit.vue
  src/pages/ContestTeamNew.vue
  src/pages/Contests.vue
  src/pages/Event.vue
  src/pages/Project.vue
  src/pages/ProjectNew.vue
  src/pages/Projects.vue
  src/pages/UserAccountEdit.vue
  src/pages/UserAccountNew.vue
  src/pages/UserAccounts.vue
Labels: Review effort [1-5]: 3
