Repository traPtitech/traPortfolio-Dashboard, pull requests merged in 2024-07, with the labels that each got.

#289 現在設定してるサービスをselectに含める
  src/pages/UserAccountEdit.vue
Labels: Review effort [1-5]: 2

#327 日本語でのサジェストを有効に
  .github/workflows/PR-Agent.yaml
Labels: Review effort [1-5]: 1

#288 project duration直した
  src/components/Projects/ProjectMember.vue
  src/components/UI/FormProjectDuration.vue
  src/pages/Project.vue
  src/pages/ProjectNew.vue
Labels: Review effort [1-5]: 3

#334 to属性でオブジェクトを使用するように変更
  src/components/Contest/ContestTeamItem.vue
  src/components/Contest/ContestTeams.vue
  src/components/Contests/ContestItem.vue
  src/components/Events/EventItem.vue
  src/components/Layout/PageHeader.vue
  src/components/Projects/ProjectItem.vue
  src/components/User/UserProfileDesktop.vue
  src/components/User/UserProfileMobile.vue
  src/components/UserAccounts/AccountItem.vue
  src/pages/Contest.vue
  src/pages/ContestEdit.vue
  src/pages/ContestNew.vue
  src/pages/ContestTeamEdit.vue
  src/pages/ContestTeamNew.vue
  src/pages/Contests.vue
  src/pages/Event.vue
  src/pages/Project.vue
  src/pages/ProjectNew.vue
  src/pages/Projects.vue
  src/pages/UserAccountEdit.vue
  src/pages/UserAccountNew.vue
  src/pages/UserAccounts.vue
Labels: Review effort [1-5]: 3

#335 「traP広報にて言及を許可」表示を削除
  src/components/UserAccounts/AccountItem.vue
Labels: Review effort [1-5]: 1
