Repository traPtitech/traPortfolio-Dashboard, pull requests merged in 2024-06, with the labels that each got.

#310 PR-Agent導入
  .github/workflows/PR-Agent.yaml
Labels: Review effort [1-5]: 2

#312 apiの変更に対応
  src/pages/ContestTeamEdit.vue
  src/pages/ContestTeamNew.vue
  src/pages/Project.vue
  src/pages/ProjectNew.vue
Labels: Review effort [1-5]: 3

#313 不要になったのでopenapitoolsを削除
  openapitools.json
  package-lock.json
  package.json
Labels: Review effort [1-5]: 2

#302 プロジェクト削除APIがなかったので一旦消した
  src/pages/Project.vue
Labels: Review effort [1-5]: 1
