Repository traPtitech/traPortfolio-Dashboard, pull requests merged in 2024-10, with the labels that each got.

#371 :bug: get suspended users
  src/store/user.ts
Labels: Review effort [1-5]: 2

#373 impl: auto patch merge
  .github/workflows/auto-merge.yaml
Labels: Review effort [1-5]: 2

#380 fixed: repository name in `auto-merge.yaml`
  .github/workflows/auto-merge.yaml
Labels: Review effort [1-5]: 1

#384 fix: remove unnecessary dependency name flag
  .github/workflows/auto-merge.yaml
Labels: Review effort [1-5]: 1

#385 ロゴの変更
  public/favicon.ico
  src/assets/traP_logo.svg
  src/assets/traP_logo_blue.svg
  src/assets/traP_logo_full_white.svg
  src/assets/traPortfolio_dashboard_logo_full.svg
  src/assets/traPortfolio_dashboard_logo_icon.svg
  src/components/Layout/PageFooter.vue
  src/components/Layout/PageHeader.vue
Labels: Review effort [1-5]: 2

#386 Fix/formatRule
  .prettierrc
  eslint.config.js
  src/App.vue
  src/components/Contest/ContestTeams.vue
  src/components/Event/EventHostItem.vue
  src/components/Events/EventItem.vue
  src/components/Events/EventLevelMenu.vue
  src/components/Index/PageInfoPanel.vue
  src/components/Layout/ContentHeader.vue
  src/components/Layout/PageFooter.vue
  src/components/Layout/PageHeader.vue
  src/components/NavigationBar/NavigationBarFooter.vue
  src/components/NavigationBar/NavigationLinksItem.vue
  src/components/Projects/ProjectMember.vue
  src/components/UI/BaseButton.vue
  src/components/UI/Checkbox.vue
  src/components/UI/ConfirmModal.vue
  src/components/UI/EventTypeAccordion.vue
  src/components/UI/ExternalLink.vue
  src/components/UI/FormInput.vue
  src/components/UI/FormTextArea.vue
  src/components/UI/Icon.vue
  src/components/UI/LinkButton.vue
  src/components/UI/MemberInput.vue
  src/components/UI/RadioButton.vue
  src/components/UI/SearchInput.vue
  src/components/UI/ServiceAccordion.vue
  src/components/User/UserAccounts.vue
  src/components/User/UserProfileDesktop.vue
  src/components/User/UserProfileMobile.vue
  src/pages/Contest.vue
  src/pages/ContestEdit.vue
  src/pages/ContestNew.vue
  src/pages/ContestTeamEdit.vue
  src/pages/ContestTeamNew.vue
  src/pages/Contests.vue
  src/pages/Events.vue
  src/pages/Project.vue
  src/pages/ProjectNew.vue
  src/pages/Projects.vue
  src/pages/User.vue
  src/pages/UserAccountEdit.vue
  src/pages/UserAccountNew.vue
  src/pages/UserAccounts.vue
Labels: Review effort [1-5]: 3

#387 revert: removing copyright
  src/components/Layout/PageFooter.vue
Labels: Review effort [1-5]: 1
