Repository traPtitech/traPortfolio-Dashboard, pull requests merged in 2024-12, with the labels that each got.

#401 サイドバーがヘッダーを覆うように修正
  src/App.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationLinks.vue
Labels: Review effort [1-5]: 3

#403 formInput のボタンがはみ出ているのを修正
  src/components/UI/FormInput.vue
Labels: Review effort [1-5]: 1

#405 scss の import 周りを修正
  src/styles/scrollbar.scss
  src/styles/toast.scss
  vite.config.ts
Labels: Review effort [1-5]: 2

#406 ナビゲーションバーにariaCurrent追加
  src/components/NavigationBar/NavigationLinksItem.vue
Labels: Review effort [1-5]: 1
